/*
    SPDX-FileCopyrightText: 2026 VidMate AI Team
    SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
*/

#pragma once

#include <QObject>
#include <QString>
#include <QOpenGLContext>
#include <QOffscreenSurface>
#include <QOpenGLShaderProgram>
#include <QMutex>
#include <memory>

/**
 * @class ShaderValidationEngine
 * @brief Offscreen GPU validation, compilation, and template wrapping engine for
 *        AI-generated and community ShaderToy GLSL shaders.
 */
class ShaderValidationEngine : public QObject
{
    Q_OBJECT

public:
    enum ShaderFormat {
        ShaderToy,      // void mainImage(out vec4 fragColor, in vec2 fragCoord)
        RaymarchSDF,    // float map(vec3 p) & computeMaterial(vec3 p, vec3 n)
        RawFragment     // Custom standard fragment shader
    };

    struct ValidationResult {
        bool success{false};
        QString errorLog;
        int errorLine{-1};
        QString finalGlslCode;
        QStringList detectedUniforms;
    };

    explicit ShaderValidationEngine(QObject *parent = nullptr);
    ~ShaderValidationEngine() override;

    static ShaderValidationEngine *instance();

    /**
     * @brief Validate and compile a GLSL shader snippet offscreen.
     * @param aiGlslCode The raw or snippet GLSL code generated by AI or user.
     * @param format The template wrapper to wrap the snippet in.
     * @return ValidationResult containing status and any GPU driver compiler logs.
     */
    ValidationResult validateShader(const QString &aiGlslCode, ShaderFormat format = ShaderToy);

    /**
     * @brief Wraps a snippet into a complete compilable fragment shader with standard uniforms.
     */
    QString wrapShaderSource(const QString &glslSnippet, ShaderFormat format = ShaderToy) const;

    /**
     * @brief Returns standard screen quad vertex shader source.
     */
    static QString standardVertexShader();

    /**
     * @brief Returns the default raymarching boilerplate template.
     */
    static QString standardRaymarchTemplate();

    /**
     * @brief Returns the default ShaderToy compatibility template.
     */
    static QString standardShaderToyTemplate();

private:
    bool ensureContext();

    QOpenGLContext *m_context{nullptr};
    QOffscreenSurface *m_surface{nullptr};
    bool m_ownsContext{false};
    QMutex m_mutex;
};
